### PR TITLE
s390-tools: fixing typos that were detected by 'lintian' as 'typo-in-manual-page'

### PR DESCRIPTION
**Pull request by frank-heimes**
The Static analysis tool for Debian packages "lintian" reports the following typos:
 W: s390-tools: groff-message usr/share/man/man8/lszcrypt.8.gz (line 1) 183: warning: macro 'Sr' not defined
 I: s390-tools: typo-in-manual-page usr/share/man/man8/chccwdev.8.gz line 49 havn't haven't
 I: s390-tools: typo-in-manual-page usr/share/man/man8/chzdev.8.gz line 165 configuation configuration
 I: s390-tools: typo-in-manual-page usr/share/man/man8/dasdinfo.8.gz line 50 compatibile compatible
 I: s390-tools: typo-in-manual-page usr/share/man/man8/dasdstat.8.gz line 31 "allows to" "allows one to"
 I: s390-tools: typo-in-manual-page usr/share/man/man8/ziomon_mgr.8.gz line 43 Lengthes Lengths
 I: s390-tools: typo-in-manual-page usr/share/man/man8/ziomon_util.8.gz line 56 lengh length
 I: s390-tools: typo-in-manual-page usr/share/man/man8/zipl.8.gz line 44 aditional additional
 I: s390-tools-zkey: typo-in-manual-page usr/share/man/man1/zkey-ekmfweb.1.gz line 15 "allows to" "allows one to"
 I: s390-tools-zkey: typo-in-manual-page usr/share/man/man1/zkey-kmip.1.gz line 15 manangement management
 I: s390-tools-zkey: typo-in-manual-page usr/share/man/man1/zkey-kmip.1.gz line 550 coresponds corresponds
 I: s390-tools-zkey: typo-in-manual-page usr/share/man/man1/zkey.1.gz line 1825 convertion conversion
 I: s390-tools-zkey: typo-in-manual-page usr/share/man/man1/zkey.1.gz line 466 systen system
 I: s390-tools-zkey: typo-in-manual-page usr/share/man/man1/zkey.1.gz line 69 "allows to" "allows one to"
 This PR fixes all of them.

### CODE REVIEW

**Review by steffen-maier — COMMENTED** [review]
Acked-by: Steffen Maier <maier@linux.ibm.com> # for ziomon

**Comment by ifranzki** [comment]
Acked-by: Ingo Franzki <ifranzki@linux.ibm.com> # for zkey and friends

**Comment by frank-heimes** [comment]
I've updated the commit with the changes requested by @hoeppnerj.
Please have another look.

**Comment by hoeppnerj** [comment]
> I've updated the commit with the changes requested by @hoeppnerj. Please have another look.

Thanks Frank, looks good now.

**Pull request closed without merging**
